name: "Nix"
on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
  workflow_run:
    workflows: ["Update Flake Deps"]
    types:
      - completed
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Create userSetting.nix
      run: |
        echo '{
          username        = "dev";
          hostname        = "Your-username";
          gitEmail        = "email.address@org.no";
          gitUsername     = "git-username";
          gitEditor       = "nano";
          xrandrSettings  = "--output eDP-1 --mode 1920x1080 --pos 4480x858 --rotate normal --output DP-10 --primary --mode 2560x1440 --pos 0x0 --rotate normal --output DP-11 --mode 1920x1200 --pos 2560x240 --rotate normal";
          intellijCli     = false;
          displayLink     = false;
          emacsConfig     = true;
          xrandrConfig    = false;
          citrixConfig    = false;
          wireguard       = false;
        }' > userSetting.nix
    - name: List files in directory
      run: ls -al
    - name: Install nix
      uses: cachix/install-nix-action@v20
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Setup cachix
      uses: cachix/cachix-action@v12
      with:
        name: nix-cargo-integration
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Test checks
      run: nix flake check -L --show-trace
    - name: Remove userSetting.nix
      run: rm userSetting.nix